// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import GeneratorCommandController from "./generator_command_controller"
application.register("generator-command", GeneratorCommandController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import VisibilityTogglerController from "./visibility_toggler_controller"
application.register("visibility-toggler", VisibilityTogglerController)
