// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GeneratorCommandController from "./generator_command_controller"
application.register("generator-command", GeneratorCommandController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)
