# Auto-generated from `rails new --help` via `rake rails_new:parse_options`
# Generated on: 2026-06-10 10:20:53 UTC

module RailsGenerators::AutoGeneratedConfigurationsHelper
  include RailsGenerators::ConfigurationSupport

  def rails_app_generator_configurations
    [
      ConfigurationStruct.new(
        configuration_key: "application_name",
        label: "Application name",
        description: "The name of your application",
        is_required: true,
        fieldable_name: "text_field",
        fieldable: FieldStruct.new(type: "text_field"),
        should_hide_configuration_name: true,
        default_value: "",
        flag_format: "positional",
        negative_prefix: nil,
        is_prominent: true
      ),
      ConfigurationStruct.new(
        configuration_key: "template",
        label: nil,
        description:
          "Path to some application template (can be a filesystem path or URL)",
        is_required: false,
        fieldable_name: "text_field",
        fieldable: FieldStruct.new(type: "text_field", default_value: ""),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "value",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "database",
        label: nil,
        description: "Preconfigure for selected database # #",
        is_required: false,
        fieldable_name: "dropdown_field",
        fieldable:
          FieldStruct.new(
            type: "dropdown_field",
            options: [
              %w[mysql Mysql],
              %w[trilogy Trilogy],
              %w[postgresql Postgresql],
              %w[sqlite3 Sqlite3],
              ["mariadb-mysql", "Mariadb Mysql"],
              ["mariadb-trilogy", "Mariadb Trilogy"]
            ],
            default_value: "sqlite3"
          ),
        should_hide_configuration_name: false,
        default_value: "sqlite3",
        flag_format: "value",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "javascript",
        label: nil,
        description: "Choose JavaScript approach # #",
        is_required: false,
        fieldable_name: "dropdown_field",
        fieldable:
          FieldStruct.new(
            type: "dropdown_field",
            options: [
              %w[importmap Importmap],
              %w[bun Bun],
              %w[webpack Webpack],
              %w[esbuild Esbuild],
              %w[rollup Rollup]
            ],
            default_value: "importmap"
          ),
        should_hide_configuration_name: false,
        default_value: "importmap",
        flag_format: "value",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "css",
        label: nil,
        description:
          "Choose CSS processor. Check https://github.com/rails/cssbundling-rails for more options #",
        is_required: false,
        fieldable_name: "dropdown_field",
        fieldable:
          FieldStruct.new(
            type: "dropdown_field",
            options: [
              %w[tailwind Tailwind],
              %w[bootstrap Bootstrap],
              %w[bulma Bulma],
              %w[postcss Postcss],
              %w[sass Sass]
            ],
            default_value: nil
          ),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "value",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "api",
        label: nil,
        description: "Preconfigure smaller stack for API only apps #",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: "false",
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      )
    ]
  end

  def optional_rails_app_generator_configurations
    [
      ConfigurationStruct.new(
        configuration_key: "skip-namespace",
        label: nil,
        description: "Skip namespace (affects only isolated engines) #",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: "false",
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-collision-check",
        label: nil,
        description: "Skip collision check #",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: "false",
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "ruby",
        label: nil,
        description: "Path to the Ruby binary of your choice #",
        is_required: false,
        fieldable_name: "text_field",
        fieldable:
          FieldStruct.new(
            type: "text_field",
            default_value: "/Users/cool/.asdf/installs/ruby/3.4.5/bin/ruby"
          ),
        should_hide_configuration_name: false,
        default_value: "/Users/cool/.asdf/installs/ruby/3.4.5/bin/ruby",
        flag_format: "value",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-git",
        label: nil,
        description: "Skip git init, .gitignore and .gitattributes",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-docker",
        label: nil,
        description: "Skip Dockerfile, .dockerignore and bin/docker-entrypoint",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-keeps",
        label: nil,
        description: "Skip source control .keep files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-action-mailer",
        label: nil,
        description: "Skip Action Mailer files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-action-mailbox",
        label: nil,
        description: "Skip Action Mailbox gem",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-action-text",
        label: nil,
        description: "Skip Action Text gem",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-active-record",
        label: nil,
        description: "Skip Active Record files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-active-job",
        label: nil,
        description: "Skip Active Job",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-active-storage",
        label: nil,
        description: "Skip Active Storage files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-action-cable",
        label: nil,
        description: "Skip Action Cable files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-asset-pipeline",
        label: nil,
        description: "Skip the asset pipeline setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-javascript",
        label: nil,
        description: "Skip JavaScript files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-hotwire",
        label: nil,
        description: "Skip Hotwire integration",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-jbuilder",
        label: nil,
        description: "Skip jbuilder gem",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-test",
        label: nil,
        description: "Skip test files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-system-test",
        label: nil,
        description: "Skip system test files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-bootsnap",
        label: nil,
        description: "Skip bootsnap gem",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-dev-gems",
        label: nil,
        description: "Skip development gems (e.g., web-console)",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-thruster",
        label: nil,
        description: "Skip Thruster setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-rubocop",
        label: nil,
        description: "Skip RuboCop setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-brakeman",
        label: nil,
        description: "Skip brakeman setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-bundler-audit",
        label: nil,
        description: "Skip bundler-audit setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-ci",
        label: nil,
        description: "Skip GitHub CI files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-kamal",
        label: nil,
        description: "Skip Kamal setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-solid",
        label: nil,
        description: "Skip Solid Cache, Queue, and Cable setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "dev",
        label: nil,
        description:
          "Set up the application with Gemfile pointing to your Rails checkout",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "devcontainer",
        label: nil,
        description: "Generate devcontainer files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "edge",
        label: nil,
        description:
          "Set up the application with a Gemfile pointing to the 8-1-stable branch on the Rails repository",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "main",
        label: nil,
        description:
          "Set up the application with Gemfile pointing to Rails repository main branch",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "rc",
        label: nil,
        description:
          "Path to file containing extra configuration options for rails command",
        is_required: false,
        fieldable_name: "text_field",
        fieldable: FieldStruct.new(type: "text_field", default_value: ""),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "value",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "no-rc",
        label: nil,
        description:
          "Skip loading of extra configuration options from .railsrc file",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "minimal",
        label: nil,
        description: "Preconfigure a minimal rails app",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-bundle",
        label: nil,
        description: "Don't run bundle install",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-decrypted-diffs",
        label: nil,
        description:
          "Don't configure git to show decrypted diffs of encrypted credentials",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "help",
        label: nil,
        description: "Show this help message and quit",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      ),
      ConfigurationStruct.new(
        configuration_key: "version",
        label: nil,
        description: "Show Rails version number and quit",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: nil,
        flag_format: "positive_boolean",
        negative_prefix: nil,
        is_prominent: false
      )
    ]
  end
end
