# Auto-generated by Cursor AI from `rails new --help` output using `rake rails_new:parse_options`
# Generated on: 2025-08-20 06:26:36 UTC

module RailsGenerators::AutoGeneratedConfigurationsHelper
  ConfigurationStruct =
    Struct.new(
      :configuration_key,
      :label,
      :description,
      :is_required,
      :fieldable_name,
      :options,
      :fieldable,
      :should_hide_configuration_name,
      :default_value
    )
  FieldStruct = Struct.new(:type, :options, :default_value, keyword_init: true)

  def rails_app_generator_configurations
    [
      ConfigurationStruct.new(
        configuration_key: "application_name",
        description: "The name of your application",
        is_required: true,
        fieldable_name: "text_field",
        fieldable: FieldStruct.new(type: "text_field"),
        should_hide_configuration_name: true
      ),
      ConfigurationStruct.new(
        configuration_key: "template",
        description:
          "Path to some application template (can be a filesystem path or URL)",
        is_required: false,
        fieldable_name: "text_field",
        fieldable: FieldStruct.new(type: "text_field", default_value: ""),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "database",
        description: "Preconfigure for selected database # #",
        is_required: false,
        fieldable_name: "dropdown_field",
        fieldable:
          FieldStruct.new(
            type: "dropdown_field",
            options: [
              %w[mysql Mysql],
              %w[trilogy Trilogy],
              %w[postgresql Postgresql],
              %w[sqlite3 Sqlite3],
              ["mariadb-mysql", "Mariadb mysql"],
              ["mariadb-trilogy", "Mariadb trilogy"]
            ],
            default_value: "sqlite3"
          ),
        should_hide_configuration_name: false,
        default_value: "sqlite3"
      ),
      ConfigurationStruct.new(
        configuration_key: "javascript",
        description: "Choose JavaScript approach # #",
        is_required: false,
        fieldable_name: "dropdown_field",
        fieldable:
          FieldStruct.new(
            type: "dropdown_field",
            options: [
              %w[importmap Importmap],
              %w[bun Bun],
              %w[webpack Webpack],
              %w[esbuild Esbuild],
              %w[rollup Rollup]
            ],
            default_value: "importmap"
          ),
        should_hide_configuration_name: false,
        default_value: "importmap"
      ),
      ConfigurationStruct.new(
        configuration_key: "css",
        description:
          "Choose CSS processor. Check https://github.com/rails/cssbundling-rails for more options #",
        is_required: false,
        fieldable_name: "dropdown_field",
        fieldable:
          FieldStruct.new(
            type: "dropdown_field",
            options: [
              %w[tailwind Tailwind],
              %w[bootstrap Bootstrap],
              %w[bulma Bulma],
              %w[postcss Postcss],
              %w[sass Sass]
            ],
            default_value: ""
          ),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "api",
        description: "Preconfigure smaller stack for API only apps #",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: "false"
      )
    ]
  end

  def optional_rails_app_generator_configurations
    [
      ConfigurationStruct.new(
        configuration_key: "skip-namespace",
        description: "Skip namespace (affects only isolated engines) #",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: "false"
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-collision-check",
        description: "Skip collision check #",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: "false"
      ),
      ConfigurationStruct.new(
        configuration_key: "ruby",
        description: "Path to the Ruby binary of your choice #",
        is_required: false,
        fieldable_name: "text_field",
        fieldable: FieldStruct.new(type: "text_field", default_value: ""),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-git",
        description: "Skip git init, .gitignore and .gitattributes",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-docker",
        description: "Skip Dockerfile, .dockerignore and bin/docker-entrypoint",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-keeps",
        description: "Skip source control .keep files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-action-mailer",
        description: "Skip Action Mailer files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-action-mailbox",
        description: "Skip Action Mailbox gem",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-action-text",
        description: "Skip Action Text gem",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-active-record",
        description: "Skip Active Record files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-active-job",
        description: "Skip Active Job",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-active-storage",
        description: "Skip Active Storage files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-action-cable",
        description: "Skip Action Cable files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-asset-pipeline",
        description: "Indicates when to generate skip asset pipeline",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-javascript",
        description: "Skip JavaScript files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-hotwire",
        description: "Skip Hotwire integration",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-jbuilder",
        description: "Skip jbuilder gem",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-test",
        description: "Skip test files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-system-test",
        description: "Skip system test files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-bootsnap",
        description: "Skip bootsnap gem",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-dev-gems",
        description: "Skip development gems (e.g., web-console)",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-thruster",
        description: "Skip Thruster setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-rubocop",
        description: "Skip RuboCop setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-brakeman",
        description: "Skip brakeman setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-ci",
        description: "Skip GitHub CI files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-kamal",
        description: "Skip Kamal setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-solid",
        description: "Skip Solid Cache, Queue, and Cable setup",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "dev",
        description:
          "Set up the application with Gemfile pointing to your Rails checkout",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "devcontainer",
        description: "Generate devcontainer files",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "edge",
        description:
          "Set up the application with a Gemfile pointing to the 8-0-stable branch on the Rails repository",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "main",
        description:
          "Set up the application with Gemfile pointing to Rails repository main branch",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "rc",
        description:
          "Path to file containing extra configuration options for rails command",
        is_required: false,
        fieldable_name: "text_field",
        fieldable: FieldStruct.new(type: "text_field", default_value: ""),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "no-rc",
        description:
          "Skip loading of extra configuration options from .railsrc file",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "minimal",
        description: "Preconfigure a minimal rails app",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-bundle",
        description: "Don't run bundle install",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      ),
      ConfigurationStruct.new(
        configuration_key: "skip-decrypted-diffs",
        description:
          "Don't configure git to show decrypted diffs of encrypted credentials",
        is_required: false,
        fieldable_name: "boolean_field",
        fieldable: FieldStruct.new(type: "boolean_field", default_value: false),
        should_hide_configuration_name: false,
        default_value: ""
      )
    ]
  end
end
