module RailsGenerate
  class RailsNewConfigurationWriter
    REQUIRED_KEYS = %w[application_name template database javascript css api].freeze
    IGNORED_KEYS = %w[name].freeze

    def initialize(configurations:)
      @configurations = configurations
    end

    def write!
      filtered = @configurations.reject { |c| IGNORED_KEYS.include?(c[:configuration_key]) }
      required = filtered.select { |c| REQUIRED_KEYS.include?(c[:configuration_key]) }
                         .sort_by { |c| REQUIRED_KEYS.index(c[:configuration_key]) }
      optional = filtered.reject { |c| REQUIRED_KEYS.include?(c[:configuration_key]) }

      content = <<~RUBY
        # Auto-generated from `rails new --help` via `rake rails_new:parse_options`
        # Generated on: #{Time.current.utc}

        module RailsGenerators::AutoGeneratedConfigurationsHelper
          include RailsGenerators::ConfigurationSupport

          def rails_app_generator_configurations
            [
              #{application_name_config},
              #{required.reject { |c| c[:configuration_key] == "application_name" }.map { |c| format_configuration(c) }.join(",\n          ")}
            ]
          end

          def optional_rails_app_generator_configurations
            [
              #{optional.map { |c| format_configuration(c) }.join(",\n          ")}
            ]
          end
        end
      RUBY

      path = Rails.root.join("app/helpers/rails_generators/auto_generated_configurations_helper.rb")
      File.write(path, content)
      puts "Generated #{path}"
    end

    private

    def application_name_config
      <<~RUBY.strip
        ConfigurationStruct.new(
          configuration_key: "application_name",
          label: "Application name",
          description: "The name of your application",
          is_required: true,
          fieldable_name: "text_field",
          fieldable: FieldStruct.new(type: "text_field"),
          should_hide_configuration_name: true,
          default_value: "",
          flag_format: "positional",
          negative_prefix: nil,
          is_prominent: true
        )
      RUBY
    end

    def format_configuration(config)
      ConfigurationFormatter.format_configuration(
        config.merge(
          flag_format: config[:flag_format] || legacy_flag_format(config),
          negative_prefix: config[:negative_prefix],
          is_prominent: false,
          label: nil
        )
      )
    end

    def legacy_flag_format(config)
      return "value" unless config[:fieldable_name] == "boolean_field"

      config[:configuration_key].start_with?("skip-") ? "positive_boolean" : "value"
    end
  end
end
